In [42]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
sns.set_theme(style="darkgrid")

In [7]:
hotels = pd.read_csv('features_hotels.csv')
test_set = pd.read_csv('test_set.csv')

In [19]:
test_set = test_set.merge(hotels, on=['hotel_id','city'])
test_set.head()

,index,order_requests,city,date,language,mobile,avatar_id,hotel_id,stock,group,brand,parking,pool,children_policy
0,0,1,vilnius,21,romanian,0,1,161,46,Boss Western,J.Halliday Inn,1,0,0
1,9,2,vilnius,18,romanian,0,1,161,36,Boss Western,J.Halliday Inn,1,0,0
2,254,30,vilnius,20,romanian,1,12,161,44,Boss Western,J.Halliday Inn,1,0,0
3,263,31,vilnius,18,romanian,1,12,161,36,Boss Western,J.Halliday Inn,1,0,0
4,272,32,vilnius,16,bulgarian,0,12,161,30,Boss Western,J.Halliday Inn,1,0,0